added new scripts - screenshot,clipmngr,fzf-mod,transadd and many modification

diff --git a/.local/bin/firefox-sync b/.local/bin/firefox-sync
--- a/.local/bin/firefox-sync
+++ b/.local/bin/firefox-sync
@@ -9,41 +9,62 @@
 #Run firefox-sync rm|del|delete|remove to remove the profile/cache from memory (/tmp)
 #Dependencies : rsync and libnotify
 
-set -ex
+usage() {
+cat << END
+USAGE: $(basename "$0") [-s [profilename]]  [-d [profilename]] [-v]
 
-if [  "$1"x = "x" ]; then
-    #replace with your own browser profile
-    profile="sy2vakcj.default-esr"
-fi
+OPTIONS:
+-s|--sync    --------------- Mention the profile to sync. If no argument is provided than default profile is used.
+-d|--delete  --------------- Mention the profile to delete. If no argument is provided than default profile is used.
+-v|--verbose --------------- Verbose output.
+END
+}
+OPT=$(getopt -o hp::r::s::v --long help,profile::,remove::,sync::,verbose -a -- "$@")
+eval set -- "$OPT"
+unset OPT
+
+while true; do
+    case $1 in
+        -h|--help) usage;break;;
+        -p|--profile) PROFILE=1
+            PROFILE=$2
+            shift 2
+            continue;;
+        -r|--remove) DEL=1
+            PROFILE=$2
+            shift 2
+            break;;
+        -s|--sync) SYNC=1
+            PROFILE=$2
+            shift 2
+            break;;
+        -v|--verbose) VERBOSE=1
+            set -ex
+            shift
+            continue;;
+        --) break;;
+        '*') echo "Invalid option: $1"
+            usage;;
+    esac
+done
+
 
 profilepath=~/.mozilla/firefox
 cachepath=~/.cache/mozilla/firefox
+while true; do
+   { [ -d $profilepath ] && break;} || read -r -p "It seems the given path doesn't exist.\nEnter the absolute path (or relative path from $HOME) to firfox profile directory " profilepath
+   { [ -d $cachepath ] && break;} || read -r -p "It seems the given path doesn't exist.\nEnter the absolute path (or relative path from $HOME) to firfox cache directory " cachepath
+done
 
-[ -d $profilepath ] || { echo "Enter the absolute path (or relative path from $HOME) to firfox profile directory"; read  profilepath; }
-[ -d $cachepath ] || { echo "Enter the absolute path (or relative path from $HOME) to firfox cache directory"; read  cachepath; }
-
-
-regex="^(remove|rm|delete|del)$"
-
-if [[ "${1}" =~ $regex ]]; then
-    #compgen is bash built in: so only try this with bash
-    # arr=( $(compgen -G /tmp/firefox-\*) ) ||( echo "directory doesn't exist" && exit 1)
-    arr=( $(ls -d /tmp/ff-sync-*) ) ||( echo "directory doesn't exist" && exit 1)
-    #bash array starts at index 0 while zsh starts at 1: so change index for zsh conversion
-    arrfilter=$(echo "${arr[@]}" | sed -E 's/.*ff-sync-(.*default.*)-'"$USER"'.*/\1/')
-    rsync -av --delete --exclude .unpacked "${arr[0]}"/ "${cachepath}"/static-"$arrfilter"
-    rsync -av --delete --exclude .unpacked "${arr[1]}"/ "${profilepath}"/static-"$arrfilter"
-    rm -r ${arr[@]}
-    notify-send "Firefox removed from /tmp" "/tmp cleared of Firefox cache and profile"
-    exit 0
+if [  "$1"x = "x" -o -z $PROFILE ]; then
+    #replace with your own browser profile
+    PROFILE="sy2vakcj.default-esr"
 fi
-
-static=static-${1:-$profile}
-link=${1:-$profile}
-volatileprofile=/tmp/ff-sync-${1:-$profile}-$USER-profile
-volatilecache=/tmp/ff-sync-${1:-$profile}-$USER-cache
+static=static-${PROFILE}
+link=${PROFILE}
+volatileprofile=/tmp/ff-sync-${PROFILE}-$USER-profile
+volatilecache=/tmp/ff-sync-${PROFILE}-$USER-cache
 IFS=
-
 #loading profile
 syncff() {
     cd "$1"
@@ -58,14 +79,34 @@ syncff() {
 
     if [ -e "${link}"/.unpacked ]; then
         rsync -av --delete --exclude .unpacked ./"${link}"/ ./"${static}"
-        notify-send -t 5000 "firefox sync" "rsynced Memory $3 to Static $3"
+        notify-send -i firefox -t 5000 "firefox sync" "rsynced Memory $3 to Static $3"
     else
         rsync -av ./"${static}"/ ./"${link}"
         touch "${link}"/.unpacked
-        notify-send -t 5000 "firefox sync" "rsynced Static $3 to ZRAM $3"
+        notify-send -i firefox -t 5000 "firefox sync" "rsynced Static $3 to ZRAM $3"
     fi
 }
 
-syncff "${profilepath}" "${volatileprofile}" "profile" &
-syncff "${cachepath}"  "${volatilecache}" "cache" &
-exit 0
+delete_profile() {
+    #compgen is bash built in: so only try this with bash
+    # arr=( $(compgen -G /tmp/firefox-\*) ) ||( echo "directory doesn't exist" && exit 1)
+    arr=( $(ls -d /tmp/ff-sync-*) ) ||{ echo "directory doesn't exist"; exit 1;}
+    #bash array starts at index 0 while zsh starts at 1: so change index for zsh conversion
+    arrfilter=$(echo "${arr[@]}" | sed -E 's/.*ff-sync-(.*default.*)-'"$USER"'.*/\1/')
+    rsync -av --delete --exclude .unpacked "${arr[0]}"/ "${cachepath}"/static-"$arrfilter"
+    rsync -av --delete --exclude .unpacked "${arr[1]}"/ "${profilepath}"/static-"$arrfilter"
+    rm -r ${arr[@]}
+    notify-send -i firefox "Firefox removed from /tmp" "/tmp cleared of Firefox cache and profile"
+    exit 0
+}
+
+if (( DEL ));then
+    echo "trying to delete"
+    delete_profile
+fi
+
+if [ $# -eq 0 -o ! -z $SYNC ] ; then
+    syncff "${profilepath}" "${volatileprofile}" "profile" &
+    syncff "${cachepath}"  "${volatilecache}" "cache" &
+    exit 0
+fi
diff --git a/.local/bin/update-links b/.local/bin/update-links
--- a/.local/bin/update-links
+++ b/.local/bin/update-links
@@ -1,91 +1,269 @@
 #!/bin/bash
-# set -ex
+
+: ' Update-sync script to work with the dotfiles of crice.
+ Latest version  of the script will be available from the repo itself (path $GITROOT/.local/bin)
+ This script basically manages to copy|mv|symlink dotfiles to and fro from
+ crice to your existing dotfiles. It also offers dry running of the operations which is helpful when trying to
+ see what actually would happen if you run any operations. Check the --help output to find out usage details.
+
+ This script is available for public, as the case with the crice. Anybody can modify the script according his/her
+ own use case. You would obviously need to modify some of the optins to fit your own system settings.
+ For example the $dotdir to point to this repository in your system, the $exscript and $exconf arrays to exlcude any files
+ that you dont want.
+  '
+
 #Put the full path of the dotfile directory
 dotdir=~/packages/repos/crice
-reject=()
-#This scripst only deals with scripts/configs in $HOME,$HOME/.config/** and $HOME/.local/bin
-#The path to the dotdir configs/scripts would usually be like $HOME/path/to/dotdir/{.local,.config}
-#And you would want it symlinked to $HOME/{.config/.local}
-#So the excess path in in the first would be the pattern you would want to remove.
-#The path to the files in dotdir is substituted with ${1/$pattern} for the placement of the symlink.
-#So the  pattern to remove would be:
-#pattern="/path/to/dotdir"
+
+#Put files and directories' path  to exlcude from operation
+# exscript=("/update-links" "/firefox-sync")
+# exconf=("/profile*")
+: '
+ This scripst only deals with scripts/configs in $HOME,$HOME/.config/** and $HOME/.local/bin
+The path to the dotdir configs/scripts would usually be like $HOME/path/to/dotdir/{.local,.config}
+And you would want it symlinked to $HOME/{.config/.local}
+So the excess path in in the first would be the pattern you would want to remove.
+The path to the files in dotdir is substituted with ${1/$pattern} for the placement of the symlink.
+So the  pattern to remove would be:
+# '
+# pattern="/path/to/dotdir"
 pattern="/packages/repos/crice"
 
 usage() {
 cat << END
 
-update-links [-s] [-c] [-b] [-d <[s|sc|script]|[c|cf|config]|[b|both]>]
+update-links [-s|--symlink]<sc|cf> [-c|--cp]<sc|cf> [-m|--mv]<sc|cf> [-d|--dry-run]<slcf|slsc|cpcf|cpsc|mvcf|mvsc> [-v|--verbose] [-r|--reverse] [-h|--help]
 
 Options:
--s          ------------- Only update scripts(~/.local/bin)
--c          ------------- Only update configs(~/[.config/**]
--b          ------------- Update both configs and scripts
--d <arg>    ------------- Dry run. args could be one of 'config','script', 'both' or their short forms
+-s|--symlink <sc|cf|file1[ file2 ..]>   ---------    Performs symlinks operation
 
 <arg>:
-s|sc|script ------------- Only dry run scripts
-c|cf|config ------------- Only dry run configs
-b|both      ------------- Dry run all
+sc|script                    --------------------    Perform operation on scripts
+cf|config                    --------------------    Perform operation on configs
+file1 file2 ..               --------------------    Symlink only the given file(s)
+-c|--cp <sc|cf>              --------------------    Only update configs(~/[.config/**]
+-m|--mv <sc|cf>              --------------------    Update both configs and scripts
+-d|--dry-run <slcf|slsc|cpcf
+|cpsc|mvcf|mvsc|reverse>     --------------------    Instead of symlinking, move the files
+
+<args>:
+slcf                         --------------------    Dry run symlink of configs
+slsc                         --------------------    Dry run symlink of scripts
+cpcf                         --------------------    Dry run copying of configs
+cpsc                         --------------------    Dry run copying of scripts
+mvcf                         --------------------    Dry run moving of configs
+mvsc                         --------------------    Dry run moving of scripts
+reverse                      --------------------    Dry run --reverse
+
+-v|--verbose                 --------------------    set -x for debugging.
+-h|--help                    --------------------    Dry run. args could be one of 'config','script', 'both' or their short forms
+-r|--reverse                 --------------------    cp/mv from destination to source (i.e. ~/[,.local,.config] to $dotdir)
 END
 exit 1;
 }
-
+OPT=$(getopt -o :hs:c:m:d:vbr --long :help,symlink:,cp:mv:dry-run:verbose,backup,reverse -a -n 'update-links' -- "$@")
 [ $# -eq 0 ] && usage
 
-while getopts ':d:acsu' opt
-do
-    case "$opt" in
-        a) all=1;;
-        c) config=1;;
-        s) script=1;;
-        d) option="${OPTARG}"
-          dry=1
-          case "$option" in
-              c|cf|config) dryconfig=1;;
-              s|sc|script) dryscript=1;;
-              a|all) dryall=1;;
-              *) echo "Invalid argument: ${OPTARG}";usage;;
-          esac
-          ;;
-        u) usage ;;
-        *) echo "Invalid option: -${OPTARG}";usage;;
+eval set -- "$OPT"
+unset OPT
+
+while true;do
+    case $1 in
+        -h|--help) usage ;break;;
+        -s|--symlink) SYMLINK=1
+            case $2 in
+                sc|script) symlinkscript=1;;
+                cf|conf) symlinkconf=1;;
+                *) echo "Invalid option to -s|--symlink: $2"; usage;;
+            esac
+            shift 2
+            continue;;
+        -c|--cp) CP=1
+            case $2 in
+                sc|script) copyscript=1;;
+                cf|conf) copyconf=1;;
+                *) echo "Invalid option to -c|--cp : $2"; usage;;
+            esac
+            shift 2
+            continue;;
+        -m|--mv) MOVE=1
+            case $2 in
+                sc|script) mvscript=1;;
+                cf|conf) mvconf=1;;
+
+                *) echo "Invalid option to -m|--mv: $2";usage;;
+            esac
+            shift 2
+            continue;;
+        -d|--dry-run) DRY=1
+            case $2 in
+                slcf|symlinkconf) drysymconf=1;;
+                slsc|symscript) drysymscript=1;;
+                mvcf|mvconf) drymvconf=1;;
+                mvsc|mvscript) drymvscript=1;;
+                cpcf|cpconf) drycpconf=1;;
+                cpsc|cpscript) drycpscript=1;;
+                reverse) dryreverse=1;;
+                *) echo "Invalid option to -d|--dry-run: $2";usage;;
+            esac
+            shift 2
+            continue;;
+        -v|--verbose) set -x;shift;continue;;
+        -b|--backup) BACKUP=1;shift;continue;;
+        -r|--reverse) REVERSE=1;shift;continue;;
+        --) shift;break;;
     esac
 done
 shift $((OPTIND-1))
+
+#store all the parameterless arguments
+opts=( ${@} )
 
 rejected() {
           rejectfile=./.rejected.$1
           [  -f $rejectfile ] && mv $rejectfile $rejectfile.old
           echo -e "\t${1~~} ------- $(date)\n" >> $rejectfile
           echo "${reject[@]}" | tr ' ' '\n' >> $rejectfile
-          echo "Some files are rejected: Check rejected.$1"
+          echo "Some files are rejected: Check rejected.$1" >&2
  }
+
+dry_run() {
+    echo "dry-run: $1 $2 $3"
+}
+
+#This method handles individual files that you pass as argument
+#$1 -> real or dry; $2 -> operation; $3 -> backup ?
+parameterless_arg() {
+        for i in ${opts[@]}; do
+            srcfile=$(find $dotdir/ -name $i)
+            [ -z $srcfile ] && { echo "No such File or Directory: $i">&2; continue;}
+            [ -d $srcfile ] && { echo "$srcfile is a directory">&2; continue; }
+            if [ -f $srcfile ]; then
+                filepath=${srcfile/$pattern}
+                if [ -f $filepath ];then
+                    ft=$(file --mime-type -b $filepath)
+                    echo "file exist: $filepath - $ft"
+                fi
+                despath=$(dirname ${filepath})
+                if  [ ! -d $despath ]; then
+                    if [ $1 = "dry" ];then
+                        echo "the path doesn't exist.Creating path>&2"
+                        echo "mkdir -p $despath"
+                        dry_run "$2" "$srcfile" "$despath"
+                        continue
+                    fi
+                    mkdir -p $despath || { echo "Couldn't create path: $despath" >&2; continue;}
+                    if [ $3 = "backup" ]; then
+                        $2 --backup $srcfile $despath
+                        continue
+                    fi
+                    $2 $srcfile $despath || echo "Couldn't $2 file : $srcfile">&2
+                else
+                    if [[ $1 = "dry" ]];then
+                        dry_run "$2" "$srcfile" "$despath"
+                        continue
+                    fi
+                    if [[ "$3" = "backup" ]]; then
+                        $2 --backup $srcfile $despath
+                        continue
+                    fi
+                    $2 $srcfile $despath
+                fi
+            fi
+        done
+        exit 0
+}
 
 update() {
         m=${1/$pattern};
-        (( dry )) && { echo "dry run: ln -s $1 $m" &&  return; }
-        if ! [ -f $m ]; then
+        #dry runs are for testing without actually running the operation
+        (( drysymscript || drysymconf )) && dry_run "ln -s" "$1" "$m" && return
+        (( dryreverse )) && { [ -f "$m" ] && dry_run "mv|cp" "$m" "$1" || echo "$m doesn't exist" ; } && return
+        if (( drycpscript || drycpconf ));then
+            [ "${#opts[@]}" -gt 0 ] && parameterless_arg "dry" "cp"
+             dry_run "cp" "$1" "$m"
+             return
+        fi
+        if (( drymvscript || drymvconf ));then
+            [ "${#opts[@]}" -gt 0 ] && parameterless_arg "dry" "mv"
+            dry_run "mv" "$1" "$m"
+            return
+        fi
+        if (( symlinkscript || symlinkconf )); then
+            if  [ -f $m ]; then
+            [ "${#opts[@]}" -gt 0 ] && parameterless_arg "real" "ln -s" && return
+            unlink $m || rm $m || { reject+=( "$m" ) && return;}
+                ln -s $1 $m
+                return
+            fi
             ln -s $1 $m
             return
         fi
-        unlink $m && echo "unliked" || rm $m || { reject+=( "$m" ) && return;}
-        ln -s $1 $m && echo "linked" ;
+        if (( copyscript || copyconf )); then
+            if (( BACKUP )); then
+                [ "${#opts[@]}" -gt 0 ] && parameterless_arg "real" "cp -iuv" "backup"
+                 cp --backup -v "$1" "$m"  || reject+=( "$1" )
+                return
+            fi
+            [ "${#opts[@]}" -gt 0 ] && parameterless_arg "real" "cp"
+            cp -vu "$1" "$m" || reject+=( "$1" )
+            return
+        fi
+        #for moving files make sure all the parent directories exist in destination,
+        if (( mvscript || mvconf )); then
+            if (( REVERSE )); then
+               if [ "${#opts[@]}" -gt 0 ]; then
+                    parameterless_arg "real" "mv -iv"
+                    exit 0
+               fi
+               if [ -f "$m" ];then
+                   mv -v "$m" "$1" || reject+=( "$1" )
+                   return
+               else
+                   echo "$m doesn't exist"
+                   return
+               fi
+            fi
+            if (( BACKUP )); then
+                [ "${#opts[@]}" -gt 0 ] && parameterless_arg "real" "mv -iv" "backup"
+                mv -iv --backup -S .b4crice "$1" "$m" || reject+=( "$1" )
+                return
+            fi
+            [ "${#opts[@]}" -gt 0 ] && parameterless_arg "real" "mv -iv"
+            mv -v "$i" "$m" || reject+=( "$1" )
+        fi
+        return
     }
 
-cd $dotdir
 
-if (( script || all || dryall || dryscript )) ;then
+cd $dotdir || { echo "couldn't cd into $dotdir"; exit 1;}
+
+if (( symlinkscript || mvscript || cpscript || drycpscript || drymvscript || drysymscript || dryreverse )) ;then
     for i in $(fd . $dotdir/.local/bin --type f); do
-        update "${i}"
+        [ -z $exscript ] && { update "${i}"; continue;}
+        for ((j=0;j<${#exscript[@]};j++));do
+            if [ $(echo $i | grep "${exscript[$j]}") ];then
+                exlist="$i"
+                break
+            fi
+        done
+        [ -z $exlist ] && { update "${i}"; continue;}
+        unset exlist
     done
    [ ${#reject[@]} -gt 0 ] && rejected "scripts"
 fi
 
-unset reject
-if (( config || all || dryall || dryconfig )); then
-    for j in $(fd . $dotdir --type f --hidden --exclude .local/bin --exclude .git* --exclude .rejected*); do
-        update "${j}"
+if (( symlinkconf || mvconf || cpconf || drycpconf || drymvconf || drysymconf || dryreverse )) ;then
+    for i in $(fd . $dotdir --type f --hidden --exclude .local/bin --exclude .git --exclude .rejected*); do
+        unset exlist
+        [ -z $exconf ] && { update "${i}"; continue;}
+        for ((j=0;j<${#exconf[@]};j++));do
+            if [ $(echo $i | grep "${exconf[$j]}") ];then
+                exlist="$i"
+                break
+            fi
+        done
+        [ -z $exlist ] && { update "${i}"; continue;}
     done
 [ ${#reject[@]} -gt 0 ] && rejected "configs"
 fi
diff --git a/.local/bin/wifi_s b/.local/bin/wifi_s
--- a/.local/bin/wifi_s
+++ b/.local/bin/wifi_s
@@ -1,12 +1,29 @@
 #!/usr/bin/env bash
+# set -x
 
 #Connect to wifi with wpa_supplicant
+#Your wifi interface:
 Interface="wlo1"
-#1. make sure interface is not blocked: rfkill
-sudo rfkill unblock $(rfkill | grep wlan | cut -d' ' -f2)
+
+#Your DHCP client:can be dhclient or dhcpcd or anything
+dhcpclient="dhcpcd"
+
+ADDR=192.168.43.168
+
+#path to your wpa_supplicant.conf
+WPA_SUPPLICANTCONF=$HOME/.config/wpa/wpa_supplicant.conf
+# mkdir -p "$WPA_SUPPLICANTCONF"
+
+if [ "$1" == "s" ]; then
+    sudo wpa_cli terminate $Interface
+    sudo pkill dhcpcd
+    exit 0
+fi
+#1. make sure interface is not blocked:
+sudo rfkill unblock "$(rfkill|grep wlan|cut -d' ' -f2)"
 
 #2. initiate the interface:
-[ "$(ip link show up | grep $Interface)" ] || sudo ip link set $Interface  up
+[ "$(grep $Interface <(ip link show up ))" ] || sudo ip link set $Interface  up
 #or
 #ifconfig wlo1 up
 
@@ -16,11 +33,12 @@ sudo rfkill unblock $(rfkill | grep wlan | cut -d' ' -f2)
 #generate asterisk for passphrase prompt
 asterisk_prompt_for_passphrase() {
     unset passphrase
-    prompt="Enter Passphrase:"
-    while IFS= read -p $prompt -r -s -n 1 char
+    prompt="Enter Passphrase: "
+    while IFS= read -r -p "$prompt" -s -n 1 char
     do
         #Enter - accept passphrase
         if [[ $char == $'\0' ]] ; then
+            echo
             break
         fi
         #Backspace
@@ -28,21 +46,23 @@ asterisk_prompt_for_passphrase() {
             prompt=$'\b \b'
             passphrase="${passphrase%?}"
         else
-            prompt='*'
+            prompt="*"
             passphrase+="$char"
         fi
     done
 }
 #4. generate wpa_supplicant.conf with SSID and passphrase if it doesn't already exist:
-if ! [ -s /etc/wpa_supplicant.conf ]; then
+if ! [ -s "$WPA_SUPPLICANTCONF" ]; then
 
-    read -p "It appears no Network is configured. Would you like to configure one(y/N)? " YN
-    [[ $YN =~ [nN] || -z $NY ]] &&  exit 0;
-
-    if [[ $YN =~ [yY] ]];then
-        read -p "Entere the SSID: " SSID
+    read -r -p "It appears no Network is configured. Would you like to configure one(y/N)? " YN
+    [[ $YN =~ [nN] || -z $YN ]] &&  exit 0;
+    if [[ $YN =~ [yY] ]]; then
+        read -r -p "Would you like to control wpa_supplicant with its frontend tool wpa_cli?(y/N) " YesNo
+        [[ $YesNo =~ [Yy] ]] && echo -e "ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=$USER" >  "$WPA_SUPPLICANTCONF"
+        read -r -p "Entere the SSID: " SSID
         asterisk_prompt_for_passphrase
-        wpa_passphrase "$SSID" "$passphrase" | sudo tee -a /etc/wpa_supplicant.conf
+        wpa_passphrase "$SSID" "$passphrase" >>  "$WPA_SUPPLICANTCONF"
+        chmod 600 "$WPA_SUPPLICANTCONF"
     else
         echo "Wrong choice"
         echo "try again"
@@ -50,30 +70,32 @@ if ! [ -s /etc/wpa_supplicant.conf ]; then
     fi
 fi
 
-if [[$1 =~ [nN] ]]; then
-    read -p "Would you like to generate a new network(y/N)? " YN
-    if [[ $NY =~ [yY] ]]; then
-        read -p "Entere the SSID: " SSID
+if [[ $1 =~ [nN] ]]; then
+    read -r -p "Would you like to generate a new network(y/N)? " YN
+    if [[ $YN =~ [yY] ]]; then
+        read -r -p "Entere the SSID: " SSID
         asterisk_prompt_for_passphrase
-        wpa_passphrase "$SSID" "$passphrase" | sudo tee -a /etc/wpa_supplicant.conf
-    elif ! [[ $YN =~ [nN] || -z $YN ]];then
+        read -r -p "Would you like to control wpa_supplicant with its frontend tool wpa_cli?(y/N) " YesNo
+        [[ $YesNo =~ [Yy] ]] && echo -e "ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=$USER" >  "$WPA_SUPPLICANTCONF"
+        wpa_passphrase "$SSID" "$passphrase" >> "$WPA_SUPPLICANTCONF"
+    elif ! [[ $YN =~ [nN] || -z $YN ]]; then
         echo "Wrong choice.Try again"
         exit 1;
     fi
 fi
 
+#you may require to mention a driver wrapper with -D nl80211,wext. Refer wpa_supplicant(8)
+[ "$(sudo wpa_supplicant -c "$WPA_SUPPLICANTCONF" -i"$Interface" -B)" ] || echo "WPA Supplicant returned error $?"
 
-#5. connect to network:
-sudo wpa_supplicant -c/etc/wpa_supplicant.conf -i"$Interface" -B
+echo "WIFI Connection Established!.Checking DHCP..."
 
-#6. If dhcp client is running, start it to get the local ip:
-
-! [[ $(pidof dhcpcd) ]] && sudo dhcpcd $Interface
-
-notify-send "WIFI Connection Established!" "Connected to AP. Ping google and check"
-
-
-
-
-
-
+#6. If dhcp client is not running, start it to get a lease:
+if [[ $(pidof $dhcpclient) ]]; then
+    sudo $dhcpclient -k $Interface
+    sudo $dhcpclient $Interface
+else
+    sudo $dhcpclient $Interface
+fi
+echo "starting dhcp client ..."
+echo "dhcpcd started!"
+ping google.com -c 1 &>/dev/null && notify-send "Network is up" "enjoy"
